#!/usr/bin/env bash
# 15-keepalived-vip.sh — install keepalived VRRP for the cluster Caddy VIP.
# Phase 7 of the DL380 Gen11 cluster migration plan.
#
# Caddy runs as a DaemonSet (one pod per node) under k3s. Only ONE of those
# pods at a time is "active" at the network layer — keepalived ensures that
# a virtual IP (the VIP) is assigned to exactly one node at any moment. On
# node failure the VIP migrates within ~5s (VRRP advertisement interval).
#
# Why VRRP and not k3s LoadBalancer?
#   - k3s ships ServiceLB / Klipper-LB but those rebind on every pod restart.
#   - VRRP is OS-level; failover does not require k3s control-plane health.
#   - MetalLB would be an alternative but adds another distributed system.
#
# Topology:
#   Node A — priority 110 (highest → initial MASTER)
#   Node B — priority 100
#   Node C — priority 90
#
# VRRP authentication: AH (authentication header) with a 16-char hex password
# read from Vault at /run/vigil/secrets/keepalived_password — prevents a
# spoofed advert from a misconfigured neighbour stealing the VIP.
#
# Idempotent. Re-runs update the config + reload keepalived.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "[fatal] must run as root" >&2
  exit 2
fi

if [[ -r /etc/vigil/cluster-node.env ]]; then
  # shellcheck disable=SC1091
  source /etc/vigil/cluster-node.env
fi

NODE_NAME="${NODE_NAME:?NODE_NAME required (vigil_postgres_a|b|c)}"
NODE_IP="${NODE_IP:?NODE_IP required}"
VIP_ADDRESS="${VIP_ADDRESS:-10.50.0.250/24}"        # Cluster-edge VIP
VIP_INTERFACE="${VIP_INTERFACE:-bond0}"             # Bonded 25 GbE interface
VRRP_ROUTER_ID="${VRRP_ROUTER_ID:-42}"              # Distinct from any other VRRP groups on the LAN

# Map node name → priority. Highest wins MASTER on initial election.
case "${NODE_NAME}" in
  *_a) PRIORITY=110 ;;
  *_b) PRIORITY=100 ;;
  *_c) PRIORITY=90 ;;
  *) echo "[fatal] cannot map ${NODE_NAME} to priority" >&2; exit 3 ;;
esac

KEEPALIVED_PW_FILE="/run/vigil/secrets/keepalived_password"
[[ -r "${KEEPALIVED_PW_FILE}" ]] || {
  echo "[fatal] missing ${KEEPALIVED_PW_FILE} — run 05-secret-materialisation.sh first" >&2
  exit 4
}
KEEPALIVED_PW="$(< "${KEEPALIVED_PW_FILE}")"

log()  { printf '[keepalived-vip] %s\n' "$*"; }

# ──────────────────────────────────────────────────────────────────────────
# 1. Install keepalived
# ──────────────────────────────────────────────────────────────────────────
log "installing keepalived"
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq keepalived

# ──────────────────────────────────────────────────────────────────────────
# 2. Render the health-check script keepalived runs to decide if Caddy is up
# ──────────────────────────────────────────────────────────────────────────
install -m 0755 /dev/stdin /usr/local/sbin/vigil-caddy-check.sh <<'CHECK_EOF'
#!/usr/bin/env bash
# Returns 0 if the local Caddy pod is responding, non-zero otherwise.
# keepalived re-runs this every 2s; a non-zero exit triggers VRRP fault
# state on this node and promotes the next-priority node.
set -e
# Look for a running Caddy container. k3s/containerd lists pods via crictl
# but plain docker also works; we try both for portability.
if command -v crictl >/dev/null 2>&1; then
  caddy_running=$(crictl ps --label io.kubernetes.container.name=caddy --state Running -q 2>/dev/null | wc -l)
else
  caddy_running=$(docker ps --filter "name=caddy" --filter "status=running" -q 2>/dev/null | wc -l)
fi
[[ "${caddy_running}" -gt 0 ]] || exit 1

# Probe Caddy's admin endpoint on localhost. Caddy returns 200 on /metrics
# when it is fully booted (Prometheus exporter is built-in).
curl -fsSL --max-time 2 http://127.0.0.1:2019/metrics >/dev/null
CHECK_EOF

# ──────────────────────────────────────────────────────────────────────────
# 3. Render /etc/keepalived/keepalived.conf
# ──────────────────────────────────────────────────────────────────────────
install -d -m 0755 /etc/keepalived
cat >/etc/keepalived/keepalived.conf <<EOF
# VIGIL APEX Caddy VIP — VRRP between the 3 DL380 nodes.
# Generated by infra/host-bootstrap/15-keepalived-vip.sh on $(date -Iseconds).
# Do NOT edit by hand — re-run the script to update.

global_defs {
  router_id ${NODE_NAME}
  enable_script_security
  script_user root
  vrrp_skip_check_adv_addr
  vrrp_strict
  vrrp_garp_interval 0
  vrrp_gna_interval 0
}

vrrp_script chk_caddy {
  script "/usr/local/sbin/vigil-caddy-check.sh"
  interval 2
  fall 2          # 2 consecutive failures → FAULT state
  rise 2          # 2 consecutive successes → recover
  timeout 3
  weight 0
}

vrrp_instance VIGIL_CADDY {
  state BACKUP
  interface ${VIP_INTERFACE}
  virtual_router_id ${VRRP_ROUTER_ID}
  priority ${PRIORITY}
  advert_int 1
  preempt_delay 30
  nopreempt
  unicast_src_ip ${NODE_IP}
  unicast_peer {
    # The other two cluster nodes' interconnect IPs — the OS-level
    # cluster-node.env file is the source of truth; we hard-code here
    # because the script needs to derive the "other two" at install time.
    10.50.0.1
    10.50.0.2
    10.50.0.3
  }
  authentication {
    auth_type PASS
    auth_pass ${KEEPALIVED_PW}
  }
  virtual_ipaddress {
    ${VIP_ADDRESS}
  }
  track_script {
    chk_caddy
  }
  notify_master "/usr/local/sbin/vigil-vip-notify.sh master"
  notify_backup "/usr/local/sbin/vigil-vip-notify.sh backup"
  notify_fault "/usr/local/sbin/vigil-vip-notify.sh fault"
}
EOF
chmod 0600 /etc/keepalived/keepalived.conf

# ──────────────────────────────────────────────────────────────────────────
# 4. Notify script — writes an audit-chain row on every state transition so
#    the audit log proves which node held the VIP when each tip / dossier /
#    council vote landed.
# ──────────────────────────────────────────────────────────────────────────
install -m 0755 /dev/stdin /usr/local/sbin/vigil-vip-notify.sh <<'NOTIFY_EOF'
#!/usr/bin/env bash
set -e
state="$1"
node="$(hostname -s)"
ts="$(date -Iseconds)"

# Best-effort: write an audit row via psql on the local Postgres if it's
# reachable. If not (e.g. Postgres is the failed service), log to journal.
if PGCONNECT_TIMEOUT=2 psql "host=127.0.0.1 user=postgres dbname=vigil" \
  -c "SELECT 1" >/dev/null 2>&1; then
  psql "host=127.0.0.1 user=postgres dbname=vigil" -v ON_ERROR_STOP=1 <<SQL
INSERT INTO audit.actions
  (id, seq, action, actor, subject_kind, subject_id, occurred_at, payload, prev_hash, body_hash)
SELECT
  gen_random_uuid(),
  COALESCE((SELECT MAX(seq) FROM audit.actions), 0) + 1,
  'cluster.vip_state_change',
  'system:keepalived',
  'cluster',
  '${node}',
  now(),
  jsonb_build_object('state', '${state}', 'node', '${node}', 'ts', '${ts}'),
  COALESCE((SELECT body_hash FROM audit.actions ORDER BY seq DESC LIMIT 1), '\\x00'::bytea),
  digest('keepalived-${state}-${node}-${ts}', 'sha256');
SQL
fi

logger -t vigil-vip "VIP state changed to ${state} on ${node}"
NOTIFY_EOF

# ──────────────────────────────────────────────────────────────────────────
# 5. Enable + start
# ──────────────────────────────────────────────────────────────────────────
systemctl enable --now keepalived.service
systemctl reload keepalived.service || systemctl restart keepalived.service

log "keepalived running on ${NODE_NAME} (priority ${PRIORITY})"
log "VIP ${VIP_ADDRESS} will float between the 3 nodes; current owner:"
ip -4 -o addr show "${VIP_INTERFACE}" | grep "${VIP_ADDRESS%/*}" || log "  (not on this node — Caddy elsewhere is MASTER)"

log "smoke test: stop Caddy on the current MASTER and verify the VIP migrates within ~5s"
