/**
 * Stable human-readable ABIs for VIGILAnchor.sol and VIGILGovernance.sol.
 *
 * Hardhat compiles each contract into a full JSON ABI under
 * `contracts/typechain-types/`. This file mirrors that ABI in ethers.js
 * fragment-string form for lightweight services that don't pull typechain
 * (the dashboard read-side, the read-only governance client, the audit
 * cross-witness verifier).
 *
 * Sync rule: every state-changing function, view, public mapping accessor,
 * and event declared in the Solidity sources is mirrored here. When the
 * source changes, this file is regenerated. Drift is a contract regression
 * — the off-chain code's understanding of the on-chain surface must match
 * what the contract actually exposes, especially on the write side.
 *
 * Last regenerated: 2026-04-29 against contracts/contracts/VIGILGovernance.sol
 * + contracts/contracts/VIGILAnchor.sol post-commit `dab20ea`.
 */

/* ============================================================================
 * VIGILAnchor — append-only registry of audit-chain root commitments.
 * ==========================================================================*/

export const VIGIL_ANCHOR_ABI = [
  // Write side
  'function commit(uint256 fromSeq, uint256 toSeq, bytes32 rootHash) external',
  'function rotateCommitter(address newCommitter) external',

  // Public state accessors (auto-generated by Solidity)
  'function committer() view returns (address)',
  'function lastToSeq() view returns (uint256)',

  // Views
  'function getCommitment(uint256 commitmentId) view returns (uint256 fromSeq, uint256 toSeq, bytes32 rootHash, address committedBy, uint256 timestamp)',
  'function totalCommitments() view returns (uint256)',

  // Ownable2Step surface (inherited from OZ)
  'function owner() view returns (address)',
  'function pendingOwner() view returns (address)',
  'function transferOwnership(address newOwner) external',
  'function acceptOwnership() external',
  'function renounceOwnership() external',

  // Events
  'event Anchored(uint256 indexed commitmentId, uint256 fromSeq, uint256 toSeq, bytes32 rootHash, address indexed committer)',
  'event CommitterRotated(address indexed previousCommitter, address indexed newCommitter)',
  'event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
] as const;

/* ============================================================================
 * VIGILGovernance — 5-pillar 3-of-5 escalation council with commit-reveal
 * proposal opening (anti-front-running, SRD §22.6).
 * ==========================================================================*/

export const VIGIL_GOVERNANCE_ABI = [
  // ---- Member management (admin-only) -----------------------------------
  'function addMember(address account, uint8 pillar) external',
  'function removeMember(uint8 pillar) external',

  // ---- Commit-reveal proposal opening -----------------------------------
  // 1. Caller commits keccak256(abi.encode(findingHash, uri, salt, msg.sender))
  // 2. Wait REVEAL_DELAY (2 minutes)
  // 3. Reveal via openProposal(findingHash, uri, salt)
  'function commitProposal(bytes32 commitment) external',
  'function openProposal(bytes32 findingHash, string uri, bytes32 salt) external returns (uint256 idx)',

  // ---- Voting -----------------------------------------------------------
  'function vote(uint256 proposalIndex, uint8 choice, bytes32 reason) external',
  'function settleExpiredProposal(uint256 proposalIndex) external',

  // ---- Constants & public state accessors -------------------------------
  'function ADMIN_ROLE() view returns (bytes32)',
  'function PILLAR_COUNT() view returns (uint8)',
  'function QUORUM_REQUIRED() view returns (uint8)',
  'function VOTE_WINDOW() view returns (uint64)',
  'function REVEAL_DELAY() view returns (uint256)',
  'function commitments(address proposer, bytes32 commitment) view returns (uint64 commitBlockTimestamp)',
  'function memberByPillar(uint8 pillar) view returns (address account, uint8 pillarOut, bool active)',
  'function memberByAccount(address account) view returns (address accountOut, uint8 pillar, bool active)',
  'function votedChoice(uint256 proposalIndex, address voter) view returns (uint8 choicePlusOne)',
  'function recuseReason(uint256 proposalIndex, address voter) view returns (bytes32 reason)',

  // ---- Views ------------------------------------------------------------
  'function getProposal(uint256 proposalIndex) view returns (bytes32 findingHash, string uri, uint8 state, uint256 openedAt, uint256 closesAt, uint8 yes, uint8 no, uint8 abstain, uint8 recuse)',
  'function totalProposals() view returns (uint256)',
  'function isPillarMember(address account) view returns (bool, uint8)',
  'function pillarOf(address account) view returns (uint8)',
  'function quorumRequired() view returns (uint8)',

  // ---- AccessControl surface (inherited from OZ) ------------------------
  'function hasRole(bytes32 role, address account) view returns (bool)',
  'function getRoleAdmin(bytes32 role) view returns (bytes32)',
  'function grantRole(bytes32 role, address account) external',
  'function revokeRole(bytes32 role, address account) external',
  'function renounceRole(bytes32 role, address callerConfirmation) external',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)',

  // ---- Events -----------------------------------------------------------
  'event ProposalCommitted(address indexed proposer, bytes32 commitment, uint64 commitBlockTimestamp)',
  'event ProposalOpened(uint256 indexed proposalIndex, bytes32 findingHash, address indexed proposer, string uri)',
  'event VoteCast(uint256 indexed proposalIndex, address indexed voter, uint8 choice, uint8 pillar, bytes32 recuseReason)',
  'event ProposalEscalated(uint256 indexed proposalIndex)',
  'event ProposalDismissed(uint256 indexed proposalIndex)',
  'event ProposalExpired(uint256 indexed proposalIndex)',
  'event MemberAdded(address indexed account, uint8 pillar)',
  'event MemberRemoved(address indexed account, uint8 pillar)',

  // AccessControl events
  'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
  'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
  'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
] as const;

/* ============================================================================
 * Enum mirrors — keep in sync with the on-chain definitions.
 * ==========================================================================*/

export type Pillar = 'governance' | 'judicial' | 'civil_society' | 'audit' | 'technical';
export const PILLAR_ID: Record<Pillar, number> = {
  governance: 0,
  judicial: 1,
  civil_society: 2,
  audit: 3,
  technical: 4,
};
export const VOTE_CHOICE = { YES: 0, NO: 1, ABSTAIN: 2, RECUSE: 3 } as const;
export const PROPOSAL_STATE = { OPEN: 0, ESCALATED: 1, DISMISSED: 2, EXPIRED: 3 } as const;

/** Commit-reveal delay — must wait this long after `commitProposal` before
 *  the matching `openProposal` will succeed. Mirrors `REVEAL_DELAY` constant
 *  in VIGILGovernance.sol. */
export const REVEAL_DELAY_SECONDS = 120; // 2 minutes
