import { Ids } from '@vigil/shared';

import { registerPattern } from '../registry.js';

import type { PatternDef } from '../types.js';

/**
 * P-D-001 — Ghost project.
 *
 * Fires when satellite imagery (Sentinel / Maxar) shows no construction
 * activity at the project coordinates within the contractual completion
 * window. The strongest signal in category D — combined with a treasury
 * disbursement event, posterior often exceeds 0.85 alone.
 *
 * For Phase 1 this pattern reads pre-computed satellite verification events
 * (kind=satellite_imagery, payload.activity_score ∈ [0..1]) which are
 * generated by an out-of-band satellite worker (Phase 1.5 / Phase 2 GIS sub-pipeline).
 */

const PATTERN_ID = Ids.asPatternId('P-D-001');

const definition: PatternDef = {
  id: PATTERN_ID,
  category: 'D',
  subjectKinds: ['Project'],
  title_fr: 'Projet fantôme — non vérifié au sol',
  title_en: 'Ghost project — unverified on the ground',
  description_fr:
    "Aucune activité de construction détectée par imagerie satellitaire dans la fenêtre contractuelle.",
  description_en:
    'No construction activity detected by satellite imagery during the contractual window.',
  defaultPrior: 0.45,
  defaultWeight: 0.95,
  status: 'live',

  async detect(subject, ctx) {
    const sat = subject.events.find((e) => e.kind === 'satellite_imagery' || e.kind === 'investment_project');
    if (!sat) return empty('no satellite verification event');
    const activity =
      typeof sat.payload['activity_score'] === 'number' ? (sat.payload['activity_score'] as number) : null;
    if (activity === null) return empty('activity_score missing');
    const disb = subject.events.find((e) => e.kind === 'treasury_disbursement' || e.kind === 'payment_order');
    if (!disb) {
      return empty('no disbursement to corroborate');
    }
    const strength = Math.max(0, Math.min(1, 1 - activity)); // activity 0 → strength 1
    ctx.logger.info('p-d-001-evaluated', { activity, strength });
    return {
      pattern_id: PATTERN_ID,
      matched: strength >= 0.5,
      strength,
      contributing_event_ids: [sat.id, disb.id],
      contributing_document_cids: [...sat.document_cids, ...disb.document_cids],
      rationale: `satellite-activity=${activity.toFixed(2)}, disbursement present`,
    };
  },
};

function empty(reason: string) {
  return {
    pattern_id: PATTERN_ID,
    matched: false,
    strength: 0,
    contributing_event_ids: [],
    contributing_document_cids: [],
    rationale: reason,
  };
}

registerPattern(definition);
export default definition;
