{{- if .Values.etcd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "etcd-headless") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "etcd") | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "vigil-apex.componentSelector" (dict "root" . "component" "etcd") | nindent 4 }}
  ports:
    - { name: client, port: 2379, targetPort: 2379, protocol: TCP }
    - { name: peer, port: 2380, targetPort: 2380, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "etcd") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "etcd") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vigil-apex.componentSelector" (dict "root" . "component" "etcd") | nindent 4 }}
  ports:
    - { name: client, port: 2379, targetPort: 2379, protocol: TCP }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "etcd") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "etcd") | nindent 4 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "etcd") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "etcd") | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "vigil-apex.componentSelector" (dict "root" . "component" "etcd") | nindent 6 }}
{{- end }}
