{{- if and .Values.externalSecrets.enabled .Values.postgres.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "postgres-secret") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "vigil-apex.componentName" (dict "root" . "component" "vault-store") }}
    kind: SecretStore
  target:
    name: {{ include "vigil-apex.componentName" (dict "root" . "component" "postgres-secret") }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: vigil/postgres
        property: password
{{- end }}
