{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil-apex.componentName" (dict "root" . "component" "vault") }}
  labels:
    {{- include "vigil-apex.componentLabels" (dict "root" . "component" "vault") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vigil-apex.componentSelector" (dict "root" . "component" "vault") | nindent 4 }}
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201
{{- end }}
