/**
 * Public /verify surface — audit-chain root + escalation metadata only.
 * NEVER entity names without a 4-of-5 council vote (W-15 fix).
 */
export const dynamic = 'force-dynamic';

export default function VerifyPage(): JSX.Element {
  return (
    <main>
      <h1>VIGIL APEX — Public verification</h1>
      <p>
        Anyone may verify that a dossier delivered to a Cameroonian institution was generated by
        VIGIL APEX, exists at a specific Polygon-anchored timestamp, and was approved by the
        5-pillar council. This page surfaces the audit-chain root and per-dossier verification only.
        Findings themselves remain confidential to the receiving institution unless the council
        votes 4-of-5 for public release.
      </p>
      <h2>Verify a dossier</h2>
      <form action="/verify" method="get">
        <label htmlFor="ref">Dossier reference (VA-YYYY-NNNN):</label>{' '}
        <input id="ref" name="ref" placeholder="VA-2026-0001" pattern="VA-\d{4}-\d{4,6}" required />{' '}
        <button type="submit">Verify</button>
      </form>
      <p style={{ marginTop: 32 }}>
        <a href="/ledger">View public audit-chain checkpoints →</a>
      </p>
    </main>
  );
}
