import type { Metadata } from 'next';

/**
 * Public /verify surface — audit-chain root + escalation metadata only.
 * NEVER entity names without a 4-of-5 council vote (W-15 fix).
 *
 * Bilingual (FR primary, EN automatic) per CLAUDE.md i18n discipline.
 * Closes the /verify portion of FIND-010 from whole-system-audit doc 10.
 */
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Vérification publique · Public verification · VIGIL APEX',
  description:
    "Vérifier qu'un dossier remis à une institution camerounaise a été généré par VIGIL APEX. Verify that a dossier delivered to a Cameroonian institution was generated by VIGIL APEX.",
  robots: 'index, follow',
};

export default function VerifyPage(): JSX.Element {
  return (
    <main>
      <h1>VIGIL APEX — Vérification publique · Public verification</h1>
      <p lang="fr">
        Toute personne peut vérifier qu&apos;un dossier remis à une institution camerounaise a été
        généré par VIGIL APEX, existe à un horodatage Polygon précis, et a été approuvé par le
        conseil 5-piliers. Cette page expose la racine de la chaîne d&apos;audit et la vérification
        par dossier uniquement. Les conclusions elles-mêmes restent confidentielles à
        l&apos;institution destinataire sauf vote 4-de-5 du conseil pour publication.
      </p>
      <p lang="en">
        Anyone may verify that a dossier delivered to a Cameroonian institution was generated by
        VIGIL APEX, exists at a specific Polygon-anchored timestamp, and was approved by the
        5-pillar council. This page surfaces the audit-chain root and per-dossier verification only.
        Findings themselves remain confidential to the receiving institution unless the council
        votes 4-of-5 for public release.
      </p>
      <h2>Vérifier un dossier · Verify a dossier</h2>
      <form action="/verify" method="get">
        <label htmlFor="ref">Référence (VA-YYYY-NNNN) · Reference:</label>{' '}
        <input id="ref" name="ref" placeholder="VA-2026-0001" pattern="VA-\d{4}-\d{4,6}" required />{' '}
        <button type="submit">Vérifier · Verify</button>
      </form>
      <p style={{ marginTop: 32 }}>
        <a href="/ledger">Voir les points de contrôle publics · View public checkpoints →</a>
      </p>
    </main>
  );
}
