#!/usr/bin/env tsx
/**
 * seed-calibration — architect-only CLI for the calibration corpus
 * bootstrap (FRONTIER-AUDIT E1.2 closure helper).
 *
 * Subcommands:
 *
 *   bootstrap-synthetic [--out PATH] [--per-category N]
 *      Emits the deterministic synthetic corpus to a file. The architect
 *      uses this to sanity-check the calibration pipeline end-to-end
 *      before any real grades exist. Synthetic cases are CLEARLY marked
 *      and NEVER loaded into the production calibration_entry table.
 *
 *   skeleton-worklist [--out PATH]
 *      Emits the architect's to-grade worklist as Markdown — a short
 *      list of historical Cameroonian / CEMAC cases the architect can
 *      use as a starting point. Each row carries the citation lines the
 *      architect MUST personally retrieve before promoting the entry to
 *      a real ground_truth label.
 *
 *   check-seed PATH
 *      Parses and validates the seed.csv at PATH. Reports per-row
 *      admissibility (EXEC §23 two-source rule) and current count vs.
 *      the Phase-9 floor / density / horizon targets. Read-only — does
 *      not modify the file.
 *
 * Never writes to seed.csv. EXEC §24.2 requires architect-write only.
 * The architect copies / edits the file at the keyboard; this tool only
 * inspects and emits scaffolding.
 */

import { readFileSync, writeFileSync } from 'node:fs';

import {
  generateSyntheticCorpus,
  SKELETON_WORKLIST,
  checkEvidenceAdmissibility,
  summarisePhase9Gate,
  parseSeedCsv,
  type CalibrationEvidenceKind,
} from '../packages/shared/src/calibration/index.js';

function usage(): never {
  process.stderr.write(
    `Usage:
  seed-calibration bootstrap-synthetic [--out FILE] [--per-category N]
  seed-calibration skeleton-worklist [--out FILE]
  seed-calibration check-seed FILE
`,
  );
  process.exit(2);
}

function takeFlag(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  if (i === -1) return undefined;
  const v = args[i + 1];
  if (v === undefined) usage();
  args.splice(i, 2);
  return v;
}

function emitSyntheticCorpus(args: string[]): void {
  const outPath = takeFlag(args, '--out');
  const perCat = takeFlag(args, '--per-category');
  const perCategory = perCat === undefined ? 3 : Number(perCat);
  if (!Number.isFinite(perCategory) || perCategory < 1) {
    process.stderr.write('--per-category must be a positive integer\n');
    process.exit(2);
  }
  const corpus = generateSyntheticCorpus({ perCategory });
  const text = JSON.stringify(corpus, null, 2) + '\n';
  if (outPath) {
    writeFileSync(outPath, text);
    process.stdout.write(`wrote ${corpus.length} synthetic cases to ${outPath}\n`);
  } else {
    process.stdout.write(text);
  }
}

function emitSkeletonWorklist(args: string[]): void {
  const outPath = takeFlag(args, '--out');
  const lines: string[] = [];
  lines.push('# Calibration Skeleton Worklist');
  lines.push('');
  lines.push(
    '_Generated by `scripts/seed-calibration.ts skeleton-worklist`. ' +
      'EXEC §23: each row is a TO-GRADE entry, not a pre-graded label._',
  );
  lines.push('');
  for (const row of SKELETON_WORKLIST) {
    lines.push(`## ${row.case_label}`);
    lines.push('');
    lines.push(`- Year: **${row.case_year}**`);
    lines.push(`- Region: **${row.region ?? 'cross-region / cross-border'}**`);
    lines.push(`- Suggested category: **${row.suggested_category}**`);
    lines.push(`- Publicly contested: **${row.publicly_contested ? 'yes' : 'no'}**`);
    lines.push('- Citation lines to retrieve & verify:');
    for (const c of row.citation_lines) {
      lines.push(`  - ${c}`);
    }
    lines.push('');
  }
  const text = lines.join('\n');
  if (outPath) {
    writeFileSync(outPath, text);
    process.stdout.write(`wrote ${SKELETON_WORKLIST.length} skeleton rows to ${outPath}\n`);
  } else {
    process.stdout.write(text);
  }
}

function checkSeed(args: string[]): void {
  const path = args[0];
  if (!path) usage();
  const text = readFileSync(path, 'utf8');
  const rows = parseSeedCsv(text);
  process.stdout.write(`parsed ${rows.length} rows from ${path}\n`);

  let admissibleCount = 0;
  for (const r of rows) {
    if (r.ground_truth === 'pending') continue;
    const kinds = r.ground_truth_evidence.map((e) => e.kind as CalibrationEvidenceKind);
    const check = checkEvidenceAdmissibility(kinds);
    if (!check.admissible) {
      process.stdout.write(`[INADMISSIBLE] ${r.id} (${r.case_label}): ${check.reason}\n`);
    } else {
      admissibleCount += 1;
    }
  }
  const gate = summarisePhase9Gate(admissibleCount);
  process.stdout.write(`\nPhase-9 gate status:\n`);
  process.stdout.write(`  admissible: ${gate.current_count}\n`);
  process.stdout.write(
    `  floor=${gate.floor}, density=${gate.target_per_category_density}, horizon=${gate.long_horizon_target}\n`,
  );
  process.stdout.write(`  floor_reached: ${gate.floor_reached}\n`);
  process.stdout.write(`  cases_remaining_to_floor: ${gate.cases_remaining_to_floor}\n`);
}

function main(): void {
  const args = process.argv.slice(2);
  const cmd = args.shift();
  switch (cmd) {
    case 'bootstrap-synthetic':
      emitSyntheticCorpus(args);
      return;
    case 'skeleton-worklist':
      emitSkeletonWorklist(args);
      return;
    case 'check-seed':
      checkSeed(args);
      return;
    default:
      usage();
  }
}

main();
