#!/usr/bin/env bash
# e2e-smoke — VIGIL APEX end-to-end smoke test.
#
# Phase F (initial scaffold) + Phase I2 (Fabric extension).
#
# Pushes a contrived ARMP award fixture into the runner, asserts the
# happy path produces a finding, a counter-evidence pass, an anchor,
# AND (Phase I2) a Fabric witness commitment that matches the
# Postgres body_hash byte-for-byte. Cross-witness verifier closes the
# loop with `make verify-cross-witness`.
#
# Exit codes:
#   0  every assertion passed
#   1  Postgres / Redis / IPFS / Vault not healthy
#   2  finding never appeared
#   3  counter-evidence never written
#   4  Polygon anchor never confirmed
#   5  Fabric witness never recorded (Phase I2)
#   6  cross-witness verifier reported divergence (Phase I2)
set -euo pipefail

SMOKE_TIMEOUT_SEC="${SMOKE_TIMEOUT_SEC:-300}"
log() { printf '[e2e-smoke] %s\n' "$*"; }
fail() { printf '[e2e-smoke][FAIL] %s\n' "$*" >&2; exit "$2"; }

# 1. Compose health
log "checking core service health"
docker exec vigil-postgres pg_isready -U vigil -d vigil >/dev/null   || fail "postgres not ready" 1
docker exec vigil-redis redis-cli -a "$(cat /run/vigil/secrets/redis_password)" ping >/dev/null \
                                                                       || fail "redis not ready" 1
docker exec vigil-ipfs ipfs id >/dev/null                              || fail "ipfs not ready" 1
docker exec vigil-vault vault status -tls-skip-verify >/dev/null 2>&1 \
  || [ $? -eq 2 ] || fail "vault unreachable" 1
# Phase I2 — Fabric peer health
docker exec vigil-fabric-peer0-org1 wget -qO- http://localhost:9443/healthz >/dev/null \
  || fail "fabric peer not ready" 1
log "✓ all services healthy"

# 2. Push a fixture ARMP award envelope onto the adapter-out stream.
log "pushing ARMP fixture event"
FIXTURE_ID="$(uuidgen)"
docker exec -i vigil-redis redis-cli -a "$(cat /run/vigil/secrets/redis_password)" \
  XADD vigil:adapter:out '*' \
  body "{\"id\":\"${FIXTURE_ID}\",\"dedup_key\":\"e2e-smoke-${FIXTURE_ID}\",\"correlation_id\":\"$(uuidgen)\",\"producer\":\"e2e-smoke\",\"produced_at\":\"$(date -uIs)\",\"schema_version\":1,\"payload\":{\"id\":\"${FIXTURE_ID}\",\"source_id\":\"armp-main\",\"kind\":\"award\",\"dedup_key\":\"e2e-${FIXTURE_ID}\",\"observed_at\":\"$(date -uIs)\",\"payload\":{\"bidder_count\":1,\"procurement_method\":\"gré à gré\",\"supplier_name\":\"Société E2E SARL\",\"contract_reference\":\"E2E-${FIXTURE_ID}\"},\"document_cids\":[],\"provenance\":{\"url\":\"https://test.fixture/e2e\",\"http_status\":200,\"response_sha256\":\"$(printf %064d 0)\",\"fetched_via_proxy\":null,\"user_agent\":\"e2e-smoke/1.0\"}}}" \
  >/dev/null

# 3. Wait for a finding linked to this fixture
log "waiting for finding..."
deadline=$(( $(date +%s) + SMOKE_TIMEOUT_SEC ))
while [ "$(date +%s)" -lt $deadline ]; do
  FINDING_ID="$(docker exec -i vigil-postgres psql -U vigil -d vigil -tAc \
    "SELECT id FROM finding.finding WHERE summary_en LIKE '%E2E-${FIXTURE_ID}%' OR title_en LIKE '%E2E-${FIXTURE_ID}%' LIMIT 1")" || true
  [ -n "${FINDING_ID:-}" ] && break
  sleep 5
done
[ -n "${FINDING_ID:-}" ] || fail "no finding created within ${SMOKE_TIMEOUT_SEC}s" 2
log "✓ finding ${FINDING_ID}"

# 4. Wait for counter-evidence pass
log "waiting for counter-evidence..."
deadline=$(( $(date +%s) + 120 ))
while [ "$(date +%s)" -lt $deadline ]; do
  CE="$(docker exec -i vigil-postgres psql -U vigil -d vigil -tAc \
    "SELECT counter_evidence FROM finding.finding WHERE id = '${FINDING_ID}'")" || true
  [ -n "${CE:-}" ] && [ "${CE}" != "null" ] && break
  sleep 5
done
[ -n "${CE:-}" ] || fail "counter-evidence never landed" 3
log "✓ counter-evidence written"

# 5. Phase I2 — Fabric witness round-trip. The audit row generated by
# the finding's state transitions must surface in audit.fabric_witness
# with a matching body_hash.
log "waiting for Fabric witness..."
deadline=$(( $(date +%s) + 120 ))
while [ "$(date +%s)" -lt $deadline ]; do
  WITNESS_COUNT="$(docker exec -i vigil-postgres psql -U vigil -d vigil -tAc \
    "SELECT COUNT(*) FROM audit.fabric_witness")" || true
  [ "${WITNESS_COUNT:-0}" -gt 0 ] && break
  sleep 5
done
[ "${WITNESS_COUNT:-0}" -gt 0 ] || fail "fabric witness never recorded" 5
log "✓ fabric witness rows: ${WITNESS_COUNT}"

# 6. Phase I2 — cross-witness verifier returns clean.
log "running cross-witness verifier..."
if make -s verify-cross-witness; then
  log "✓ cross-witness clean"
else
  fail "cross-witness reported divergence (see audit-verifier-cli logs)" 6
fi

log "ALL SMOKE CHECKS PASSED for finding ${FINDING_ID}"
